spring.application.name=interview-service

spring.datasource.url=jdbc:postgresql://localhost:5432/interview_db
spring.datasource.username=interview_app
spring.datasource.password=${aleyfrag@123}

spring.jpa.hibernate.ddl-auto=none
